# File Manipulation and NumPy Array

Write a Python program to create a text file named student_scores.txt and write the data into it. 
Display the contents of the file after writing.

In [1]:
file = open("student_scores.txt", "w")
file.write("Name,Math,Science,English\n")
file.write("Ali,85,90,88\n")
file.write("Bilal,78,82,89\n")
file.write("Raza,92,87,85\n")
file.close()

file = open("student_scores.txt", "r")
content = file.read()
file.close()

print(content)

Name,Math,Science,English
Ali,85,90,88
Bilal,78,82,89
Raza,92,87,85



Read the data from student_scores.txt, extract the scores for each subject, and calculate the
average score for Math, Science, and English. Write the averages to a new file named
average_scores.txt.

In [14]:
file=open("student_scores.txt", "r")
lines=file.readlines()
file.close()

math_scores = []
science_scores = []
english_scores = []

for line in lines[1:]:
    data = line.strip().split(",")
    math_scores.append(int(data[1]))
    science_scores.append(int(data[2]))
    english_scores.append(int(data[3]))

average_math = sum(math_scores) / len(math_scores)
average_science = sum(science_scores) / len(science_scores)
average_english = sum(english_scores) / len(english_scores)

print(average_math)

file = open("average_scores.txt", "w")
file.write(f"{average_math}\n{average_science}\n{average_english}\n")
file.close()

85.0


Append a new record to student_scores.txt for a student named "David" with scores 88, 84,
and 90 in Math, Science, and English, respectively. Display the updated file content.

In [17]:
file=open("student_scores.txt", "a")
file.write("David,88,84,90\n")
file.close()

file=open("student_scores.txt", "r")
content=file.read()
print(content)

Name,Math,Science,English
Ali,85,90,88
Bilal,78,82,89
Raza,92,87,85
David,88,84,90



Write a Python program to read the contents of student_scores.txt and count the number of
students who scored above 85 in any subject.

In [20]:
file = open("student_scores.txt", "r")
lines = file.readlines()
file.close()

count = 0

for line in lines[1:]:
    data = line.strip().split(",")
    if int(data[1]) > 85 or int(data[2]) > 85 or int(data[3]) > 85:
        count += 1

print(f"Number of students who scored above 85 in any subject: {count}")

Number of students who scored above 85 in any subject: 4


Write a program to read a file data.txt containing space-separated numerical values in each
line. Convert these values into a NumPy array and calculate:
The mean of all numbers.
The maximum value in the array.

In [26]:
import numpy as np

# Creating the data.txt file with sample space-separated numbers
data = """12 34 56 78
90 23 45 67
89 12 34 56"""

file = open("data.txt", "w")
file.write(data)
file.close()

print("data.txt file created successfully.")

# Reading the file and processing the data
file = open("data.txt", "r")
lines = file.readlines()
file.close()

data_list = []

for line in lines:
    data_list.extend(map(int, line.strip().split()))

arr = np.array(data_list)

mean_value = np.mean(arr)
max_value = np.max(arr)

print(f"Mean of all numbers: {mean_value}")
print(f"Maximum value: {max_value}")

data.txt file created successfully.
Mean of all numbers: 49.666666666666664
Maximum value: 90


Create a 3x3 NumPy array with random integers between 1 and 100. Perform the following
operations:
Find the minimum value of the array.
Compute the sum of each row and each column.

In [29]:
import numpy as np

arr = np.random.randint(1, 101, size=(3, 3))

min = np.min(arr)

row = np.sum(arr, axis=1)
col = np.sum(arr, axis=0)

print("Array:")
print(arr)
print(f"Minimum value: {min}")
print(f"Sum of each row: {row}")
print(f"Sum of each column: {col}")


Array:
[[44 59 32]
 [72 45 78]
 [94 11 70]]
Minimum value: 11
Sum of each row: [135 195 175]
Sum of each column: [210 115 180]


Create a NumPy array containing the following temperatures (in Celsius): [25, 30, 35, 28, 32].
Convert this array to Fahrenheit using the formula.
Display both Celsius and Fahrenheit arrays.

In [2]:
import numpy as np

celsius_temps = np.array([25, 30, 35, 28, 32])
fahrenheit_temps = (celsius_temps * 9/5) + 32

print("Celsius:", celsius_temps)
print("Fahrenheit:", fahrenheit_temps)


Celsius: [25 30 35 28 32]
Fahrenheit: [77.  86.  95.  82.4 89.6]


Create a NumPy array of shape (4, 4) with random integers between 10 and 50. Replace all even
numbers in the array with -1. Display the modified array.

In [5]:
import numpy as np

array = np.random.randint(10, 50, (4, 4))
array[array % 2 == 0] = -1

print("Modified Array:")
print(array)


Modified Array:
[[-1 35 -1 -1]
 [-1 37 -1 -1]
 [-1 27 45 19]
 [17 -1 -1 -1]]


Create a 1D NumPy array containing 10 equally spaced numbers between 0 and 1. Reshape it into
a 2x5 matrix and calculate:
• The mean of each row.
• The standard deviation of the entire matrix.

In [14]:
import numpy as np

array = np.linspace(0, 1, 10)  
matrix = array.reshape(2, 5)  
row_means = np.mean(matrix, axis=1) 
matrix_std = np.std(matrix)         

print("Matrix:\n", matrix)
print("Row Means:", row_means)
print("Standard Deviation of Matrix:", matrix_std)

Matrix:
 [[0.         0.11111111 0.22222222 0.33333333 0.44444444]
 [0.55555556 0.66666667 0.77777778 0.88888889 1.        ]]
Row Means: [0.22222222 0.77777778]
Standard Deviation of Matrix: 0.31914236925211265


Given a 2D NumPy array of shape (5, 3) containing random integers, write code to:
• Identify and display the maximum value in each column.
• Calculate the sum of all elements in the array.

In [16]:
array = np.random.randint(1, 100, (5, 3)) 
column_max = np.max(array, axis=0)         
total_sum = np.sum(array)                  

print("Array:\n", array)
print("Maximum Values in Each Column:", column_max)
print("Sum of All Elements:", total_sum)

Array:
 [[ 5 51 54]
 [38 44 38]
 [26  7  8]
 [65 94 15]
 [10 89 80]]
Maximum Values in Each Column: [65 94 80]
Sum of All Elements: 624


Write a Python program to create a file named sales_data.txt. Read the file and load the Sales column into a NumPy array.
• Calculate and display the following using the NumPy array

In [18]:
import numpy as np

with open("sales_data.txt", "w") as file:
    file.write("Region,Product,Sales\n")
    file.write("North,ProductA,200\n")
    file.write("South,ProductB,150\n")
    file.write("East,ProductA,300\n")
    file.write("West,ProductC,250\n")

data = np.genfromtxt("sales_data.txt", delimiter=",", skip_header=1, dtype=None, encoding="utf-8")
sales = np.array([int(row[2]) for row in data])

total_sales = np.sum(sales)
average_sales = np.mean(sales)
region_max_sales = data[np.argmax(sales)][0]

print("Total Sales:", total_sales)
print("Average Sales:", average_sales)
print("Region with Maximum Sales:", region_max_sales)

Total Sales: 900
Average Sales: 225.0
Region with Maximum Sales: East


Create a file named matrix_data.txt. Write a Python program to read this file and convert its content into a 2D NumPy array.
Perform the following operations on the array:
• Find the determinant of the matrix.
• Calculate the transpose of the matrix.
• Save the transpose into a new file named matrix_transpose.txt

In [21]:
import numpy as np

with open("matrix_data.txt", "w") as file:
    file.write("1 2 3\n")
    file.write("4 5 6\n")
    file.write("7 8 9\n")

matrix = np.loadtxt("matrix_data.txt")
determinant = np.linalg.det(matrix)
transpose = matrix.T
np.savetxt("matrix_transpose.txt", transpose, fmt="%d")

print("Original Matrix:\n", matrix)
print("Determinant of the Matrix:", determinant)
print("Transpose of the Matrix:\n", transpose)

Original Matrix:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Determinant of the Matrix: -9.51619735392994e-16
Transpose of the Matrix:
 [[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]
